name: Neurite Desktop Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (draft, prerelease, final)'
        required: false
        default: 'draft'

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.version.outputs.timestamp }}
      tag: ${{ steps.version.outputs.tag }}
      draft: ${{ steps.version.outputs.draft }}
      prerelease: ${{ steps.version.outputs.prerelease }}
    steps:
      - name: Generate timestamped version
        id: version
        run: |
          timestamp=$(date +'%Y.%m.%d.%H%M%S')
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "tag=electron-$timestamp" >> $GITHUB_OUTPUT

          case "${{ github.event.inputs.release_type }}" in
            draft)
              echo "draft=true" >> $GITHUB_OUTPUT
              echo "prerelease=false" >> $GITHUB_OUTPUT
              ;;
            prerelease)
              echo "draft=false" >> $GITHUB_OUTPUT
              echo "prerelease=true" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "draft=false" >> $GITHUB_OUTPUT
              echo "prerelease=false" >> $GITHUB_OUTPUT
              ;;
          esac

  build:
    needs: set-version
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      RELEASE_VERSION: ${{ needs.set-version.outputs.timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: electron

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AppImage dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2

      - name: Install dependencies
        run: npm install

      - name: Embed version into build
        run: npm run set-version "${{ env.RELEASE_VERSION }}"

      - name: Build Electron app
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest)  npm run build -- --linux --publish=never ;;
            macos-latest)   npm run build -- --mac --publish=never ;;
            windows-latest) npm run build -- --win --publish=never ;;
          esac

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/**/*.dmg
            dist/**/*.exe
            dist/**/*.AppImage

  release:
    needs:
      - build
      - set-version
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ needs.set-version.outputs.tag }}
      RELEASE_VERSION: ${{ needs.set-version.outputs.timestamp }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          path: dist

      - name: Flatten dist structure
        run: |
          mkdir flat
          find dist -type f \( -name '*.dmg' -o -name '*.exe' -o -name '*.AppImage' \) -exec cp {} flat/ \;

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Neurite Desktop ${{ env.RELEASE_VERSION }}
          body: Electron desktop release for version ${{ env.RELEASE_VERSION }}.
          draft: ${{ needs.set-version.outputs.draft }}
          prerelease: ${{ needs.set-version.outputs.prerelease }}
          files: flat/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs:
      - release
      - set-version
    if: needs.set-version.outputs.draft == 'false' && needs.set-version.outputs.prerelease == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete old electron-* releases (keep latest)
        run: |
          gh release list --limit 100 --json tagName,createdAt \
            | jq -r '.[] | select(.tagName | startswith("electron-")) | "\(.createdAt) \(.tagName)"' \
            | sort -r \
            | tail -n +2 \
            | awk '{print $2}' \
            | xargs -r -n 1 gh release delete -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
